stages:
  - build

build_lecv:
  stage: build
  script: |
    docker run --rm -v $CI_PROJECT_DIR:/lecertvend -w /lecertvend -e XUID=$UID reg.omt.cx/golang:1.19.2-alpine sh build.sh
    if [[ ! -z "${CI_COMMIT_TAG}" ]]; then
      mv lecertvend lecertvend-${CI_COMMIT_TAG}
    fi
  artifacts:
    name: lecertvend
    paths:
      - lecertvend*
